apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hubble-cert-kv
  namespace: kube-system
spec:
  provider: azure
  secretObjects:
    - secretName: hubble-ingress-tls
      type: kubernetes.io/tls
      data:
        - objectName: all-in-one-cert
          key: tls.key
        - objectName: all-in-one-cert
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    clientID: 980fd6bd-d343-405c-a52e-79c8418a2d90
    keyvaultName: my-secure-keyvault-aks
    tenantId: 604f1a96-cbe8-43f8-abbf-f8eaf5d85730
    objects: |
      array:
        - |
          objectName: all-in-one-cert
          objectType: secret
          objectVersion: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-sa
  namespace: kube-system
  annotations:
    azure.workload.identity/client-id: "980fd6bd-d343-405c-a52e-79c8418a2d90"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-cert-refresher
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-refresher
  template:
    metadata:
      labels:
        app: cert-refresher
    spec:
      serviceAccountName: hubble-sa
      containers:
        - name: refresher
          image: busybox
          command: ["sleep", "3600"]
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "hubble-cert-kv"

