apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: victoriametrics-vmalertmanager-cnp
  namespace: victoriametrics
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmalertmanager
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: ingress-nginx
            k8s:io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
            - port: "9093"
              protocol: TCP
  egress:
    - toFQDNs:
        - matchName: hooks.slack.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

---


apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: victoriametrics-vmselect-cnp
  namespace: victoriametrics
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmselect
      app.kubernetes.io/instance: vmks-victoria-metrics-k8s-stack
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: ingress-nginx
            k8s:io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
            - port: "8481"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: jaeger
            app.kubernetes.io/component: query
            app.kubernetes.io/instance: jaeger
      toPorts:
        - ports:
            - port: "8481"
              protocol: TCP
---

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: victoriametrics-pods-cnp
  namespace: victoriametrics
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: victoriametrics

  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: victoriametrics

    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: fluentbit
            app.kubernetes.io/name: fluent-bit
      toPorts:
        - ports:
            - port: "2020"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns

    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vmagent-allow-nodes
  namespace: victoriametrics
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmagent
  egress:
    - toEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
            - port: "9100"
              protocol: TCP

    - toEndpoints:
        - matchExpressions:
            - key: k8s:io.kubernetes.pod.namespace
              operator: In
              values:
                - jaeger
            - key: app.kubernetes.io/component
              operator: In
              values:
                - agent
                - collector
                - ingester
                - query
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP


---

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vminsert-allow-otlp
  namespace: victoriametrics
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vminsert

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: opentelemetry-collector
            k8s:io.kubernetes.pod.namespace: opentelemetry
      toPorts:
        - ports:
            - port: "8480"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: victoria-operator-allow-konnectivity
  namespace: victoriametrics
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            app: konnectivity-agent
      toPorts:
        - ports:
            - port: "9443"
              protocol: TCP

