---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater-sa
  namespace: argocd
  annotations:
    azure.workload.identity/client-id: 980fd6bd-d343-405c-a52e-79c8418a2d90
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: env-secret-csi
  namespace: argocd
spec:
  provider: azure
  secretObjects:
    - secretName: env-secret
      type: Opaque
      data:
        - objectName: GIT-USERNAME
          key: GIT_USERNAME
        - objectName: GIT-PASSWORD
          key: GIT_PASSWORD
        - objectName: DR-AUTH
          key: DR_AUTH
  parameters:
    usePodIdentity: "false"
    clientID: 980fd6bd-d343-405c-a52e-79c8418a2d90
    keyvaultName: my-secure-keyvault-aks
    tenantId: 604f1a96-cbe8-43f8-abbf-f8eaf5d85730
    objects: |
      array:
        - |
          objectName: GIT-USERNAME
          objectType: secret
        - |
          objectName: GIT-PASSWORD
          objectType: secret
        - |
          objectName: DR-AUTH
          objectType: secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-image-updater
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater-sa
    namespace: argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-image-updater
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-image-updater
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater-sa
    namespace: argocd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://hub.docker.com/repositories/yassmineljeri
      credentials: env:DR_AUTH
      defaultns: library
      default: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater-sa
      containers:
        - name: argocd-image-updater
          image: quay.io/argoprojlabs/argocd-image-updater:v0.17.0
          imagePullPolicy: Always
          args: ["run","--interval=30s"]
          env:
            - name: DR_AUTH
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DR_AUTH

            - name: ARGOCD_ENV_GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: GIT_USERNAME
            - name: ARGOCD_ENV_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: GIT_PASSWORD
            - name: IMAGE_UPDATER_LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: argocd-image-updater-config
                  key: log.level
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /app/config
              name: image-updater-conf
            - mountPath: /tmp
              name: tmp
            - mountPath: "/mnt/secrets-store"
              name: secrets-store-inline
              readOnly: true
      volumes:
        - name: image-updater-conf
          configMap:
            name: argocd-image-updater-config
        - name: tmp
          emptyDir: {}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: env-secret-csi


