apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pull-secrets-scaledobject
  namespace: devops-agent
spec:
  scaleTargetRef:
    name: pull-secrets-deployment
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: azure-pipelines
      metadata:
        organizationURLFromEnv: organizationURL
        poolID: "10"
        personalAccessTokenFromEnv: personalAccessToken
        targetPipelinesQueueLength: "1"
        activationTargetPipelinesQueueLength: "0"
      authenticationRef:
        name: azdo-kv-auth