apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-self-pod-cleanup
  namespace: devops-agent
subjects:
  - kind: ServiceAccount
    name: kv-sa
    namespace: devops-agent
roleRef:
  kind: Role
  name: self-pod-cleanup
  apiGroup: rbac.authorization.k8s.io