apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: credentials-env
  namespace: velero
spec:
  provider: azure
  secretObjects:
    - secretName: velero-ingress-tls
      type: kubernetes.io/tls
      data:
        - objectName: all-in-one-cert
          key: tls.key
        - objectName: all-in-one-cert
          key: tls.crt
    - secretName: credentials
      type: Opaque
      data:
        - objectName: Velero-User        # must match Key Vault secret name
          key: user
        - objectName: Velero-Password    # must match Key Vault secret name
          key: password
  parameters:
    usePodIdentity: "false"
    clientID: f1e04b39-1dab-49cc-bf87-f96f45925d56
    keyvaultName: my-secure-keyvault-aks
    tenantId: 604f1a96-cbe8-43f8-abbf-f8eaf5d85730
    objects: |
      array:
        - |
          objectName: Velero-User
          objectType: secret
        - |
          objectName: Velero-Password
          objectType: secret
        - |
          objectName: all-in-one-cert
          objectType: secret
          objectVersion: ""
